# Generated by Django 5.0 on 2023-12-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoappv3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done_status',
            field=models.BooleanField(),
        ),
    ]
