version: "3"

services:

  todolist-django-sqlite:
    image: "todolist:1.1"
    env_file:
      - ".env.docker"
    volumes:
      - todolist_sqlite_volume:/home/todolist/persistence/
      - static:/static/
    
  
  todolist-redis:
    image: "redis:7.2.3-alpine3.19"
  
  
  nginx_reverse_proxy:
    image: "nginx_configured:1.25.3-alpine3.18"
    ports:
      - "80:80"
    depends_on:
      - todolist-django-sqlite
    volumes:
      - static:/static/

volumes:
  todolist_sqlite_volume:
  static: