# Generated by Django 5.0 on 2023-12-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoappv2', '0002_alter_todolist_done_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='activity_description',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
