# Generated by Django 5.0 on 2023-12-17 20:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(2, message='tag name must be at least 2 characters.'), django.core.validators.MaxLengthValidator(16, message='tag name must be less than 12 characters.')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Username must be at least 4 characters.'), django.core.validators.MaxLengthValidator(12, message='Username must be less than 12 characters.')])),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4, message='task description must be at least 4 characters.'), django.core.validators.MaxLengthValidator(128, message='task description must be less than 128 charatacters.')])),
                ('is_complete', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deadline_at', models.DateTimeField()),
                ('Tag_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoappv4.tag')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoappv4.user')),
            ],
        ),
    ]
