# Generated by Django 5.0 on 2024-01-10 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_token_tokenblocklist_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenblocklist',
            name='refresh_token',
            field=models.CharField(max_length=8192, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
    ]
