# Generated by Django 5.0 on 2023-12-19 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoappv4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='tag name must be at least 2 characters.'), django.core.validators.MaxLengthValidator(16, message='tag name must be less than 12 characters.')]),
        ),
    ]
